### YamlMime:ModuleUnit
uid: 
metadata:
  title: Outline the application
  description: Identify what the command line application will do and the approach to implement it.
  ms.date: 
  author: meaghanlewis
  ms.author: shanama
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: Introduction
durationInMinutes: 1
content: |
  [!include[](includes/2-application-outline.md)]
